### ISSUE TITLE
Build from source failed

### ISSUE THREAD

**Issue by IdentySergey** [arenadata/pxf-archive#137]
The documentation states that pxf requires java 8/11 to work, but the current build 6.11.0_arenadata17 requires JAVA 17. Is this a bug or a forced update of the JAVA version? Will there be problems with installation on centos 7? (Build failed with java-8)

**Comment by ayleen** [comment]
Greetings, @IdentySergey.

We apologize for the delayed response.

Starting with version 6.11.0_arenadata17, PXF requires Java 17 due to necessary security updates. The documentation will be updated shortly to reflect this change.

Since there is no JDK 17 installer for CentOS 7, you will need to build JDK 17 from the sources to use it with PXF on this OS.

If you have any other questions, please feel free to reach out to me. Thank you!

**Comment by IdentySergey** [comment]
@ayleen thanks for the answer.

I think it is very important to point this out so as not to get into a situation where you build an open version and get a non-working component after installing it on a cluster.

I think that after correcting the documentation this problem can be closed.

**Comment by iamlapa** [comment]
Documentation has been updated as part of these changes: https://github.com/arenadata/pxf/pull/139.
